config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]


  resources :blogs do
    resources :comments, module: :blogs, only: %i[index create]
  end

  devise_scope :user do
    get "users", to: "devise/sessions#new"
  end

  devise_for :users, path: '',
                path_names: {
                sign_in: 'login',
                sign_out: 'logout',
                sign_up: 'register'
                            }

  resources :portfolios, except: [:show]

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body, :topic_id

  has_rich_text :body
  has_many_attached :images, dependent: :destroy

  has_many :comments, as: :commentable, dependent: :destroy, counter_cache: :commentable_count

  belongs_to :topic, optional: true

  def self.special_blogs
    all
  end

  def self.featured_blogs
    limit(2)
  end

  def self.recent
    order("updated_at DESC")
  end
end

app/controllers/blogs/comments_controller.rb
class Blogs::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
      @commentable = Blog.friendly.find(params[:blog_id])
    end
end

app/controllers/blogs_controller.rb
class BlogsController < CommentsController
  before_action :set_blog, only: %i[ show edit update destroy toggle_status ]
  before_action :set_sidebar_topics, except: [:update, :create, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: { except: [:destroy, :new, :create, :update, :edit, :toggle_status] }, admin: :all, testing: { except: [:destroy, :create, :update]}

  def index
    if logged_in?(:admin) || logged_in?(:testing)
      @blogs = Blog.recent.with_rich_text_body_and_embeds.page(params[:page]).per(5)
    else
      @blogs = Blog.published.recent.with_rich_text_body_and_embeds.page(params[:page]).per(5)
    end
    @page_title = "My Portfolio Blog"
  end

  def show
    if logged_in?(:admin) || logged_in?(:testing) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new
      @page_title = @blog.title
      @seo_keywords = @blog.body
    else redirect_to blogs_path, notice: 'You are not authorized to access this page.'
    end
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), success: "Blog was successfully created." }
      else
        flash[:danger] = "Blog must have title, body and topic."
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), success: "Blog was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, status: :see_other }
    end
  end

  def toggle_status
    if @blog.draft? && logged_in?(:admin)
      @blog.published!
    elsif @blog.published? && logged_in?(:admin)
      @blog.draft!
    end
    redirect_to blogs_url, success: 'Post status has been updated.'
  end

  private

  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :body, :topic_id, :status, images: [])
  end

  def set_sidebar_topics
    @side_bar_topics = Topic.with_blogs
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper(user)
    image_tag "https://gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email.downcase)}", width: 60
  end


  def blog_status_color(blog)
    'color: red' if blog.draft?
  end

end

app/views/blogs/_admin_actions.html.erb
  
<% if authorized_to %>
  <nav class="breadcrumb blogcrumb">
    <%= link_to fa_icon('file-text'), toggle_status_blog_path(blog), style: blog_status_color(blog) %>
    <%= link_to fa_icon('pencil-square-o'), edit_blog_path(blog) %>
    <%= link_to fa_icon('trash'), blog, data: { turbo_method: :delete,
                        turbo_confirm: 'Are you sure?' } %>
  </nav>
<% end %>

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title, blog %></h2>
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>

  <%= render partial: 'blogs/admin_actions', locals: { blog: blog } %>
  <div data-controller="read-more" data-controller='trix-mark' data-read-more-more-text-value="Read more" data-read-more-less-text-value="Read less">
    <p data-read-more-target="content">
      <%= truncate(blog.body.to_plain_text, length: 200) %>
    </p>
    <button data-action="read-more#toggle click->trix-mark#btnClick" class="btn btn-outline-primary" >Read more</button>
    <template data-read-more-target="full" data-trix-mark-target="readbtn">
      <%= blog.body %>
    </template>
  </div>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
        <% blog.errors.full_messages.each do |error| %>
          <%= render "shared/flash", level: :error, content: error %>
        <% end %>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, class: 'form-control', placeholder: 'Title' %>
  </div>

    <div class="form-group">
    <%= form.label :topic %>
    <%= form.collection_select(:topic_id, Topic.all, :id, :title,
                                {
                                  include_blank: true
                                },
                                class: 'form-control'
                              ) 
    %>
  </div>

  <div class="form-group">
    <%= form.radio_button :status, "draft" %>
    <%= form.label :status, "Draft" %>
  
    <%= form.radio_button :status, "published" %>
    <%= form.label :status, "Published" %>
  </div>

  <div class="form-group">
    <%= form.rich_text_area :body, class: 'form-control', rows: 15, placeholder: 'Content' %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: 'btn btn-outline-primary' %>
  </div>
<% end %>  

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">

  <h1>Editing blog</h1>

  <%= render "form", blog: @blog %>

  <br>

  <div>
    <%= link_to "Show this blog", @blog %> |
    <%= link_to "Back to blogs", blogs_path %>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">

    <%= paginate @blogs %>

    <%= render @blogs %>
    
    <%= paginate @blogs %>
    
</div>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
  <h1>New blog</h1>

  <%= render "form", blog: @blog %>

  <br>

  <div>
    <%= link_to "Back to blogs", blogs_path %>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">

  <h2><%= @blog.title %></h2>

  <nav class="breadcrumb">
    <%= link_to "Home", root_path, class: 'breadcrumb-item'%>
    <%= link_to @blog.topic.title, topic_path(@blog.topic), class: 'breadcrumb-item'%>
    <span class="breadcrumb-item active"><%= @blog.title %></span>
    <% if authorized_to %>
      <span class="pull-right blogcrumb">
        <%= link_to fa_icon('pencil-square-o'), edit_blog_path(@blog) %>
        <%= link_to fa_icon('trash'), @blog, data: { turbo_method: :delete,
                          turbo_confirm: "Are you sure you want to delete this post" } %>
      </span>
    <% end %>
  </nav>

  <div>
    <p>
      <%= @blog.body %>
    </p>
    <%= render partial: 'comments/comments', locals: {commentable: @blog} %>
    <%= render partial: 'comments/form', locals: {commentable: @blog} %>
  </div>


</div>