config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]


  resources :blogs do
    resources :comments, module: :blogs, only: %i[index create]
  end

  devise_scope :user do
    get "users", to: "devise/sessions#new"
  end

  devise_for :users, path: '',
                path_names: {
                sign_in: 'login',
                sign_out: 'logout',
                sign_up: 'register'
                            }

  resources :portfolios, except: [:show]

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body

  has_rich_text :body
  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.by_position
    order("position ASC")
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: %i[ show edit update destroy move ]
  access all: [:show, :index], user: { except: [:destroy, :new, :create, :update, :edit, :move] }, admin: :all, testing: { except: [:destroy, :create, :update]}
  layout "portfolio"

  def index
    @portfolio_items = Portfolio.by_position
  end

  def new
    @portfolio_item = Portfolio.new
    @portfolio_item.technologies.build
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, success: 'Portfolio item was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, success: 'Portfolio item was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def destroy
    # Destroy the record
    @portfolio_item.destroy

    # Redirect
    #redirect_to portfolios_path, status: :see_other
    respond_to do |format|
      format.html { redirect_to portfolios_url, status: :see_other }
    end
  end

  def move
    @portfolio_item.insert_at(params[:position].to_i)
  end

  private

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :position,
                                      :subtitle,
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end
end

app/views/portfolios/_form.html.erb
<%= form_with model: @portfolio_item do |form| %>
  <% if portfolio_item.errors.any? %>
        <% portfolio_item.errors.full_messages.each do |error| %>
          <%= render "shared/flash", level: :error, content: error %>
        <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: 'form-control' %>
      </div>
      <div class="form-group">
      <label class="btn btn-primary">
        Upload an image file  <%= form.file_field :main_image, style: 'display: none;' %>
      </label>
      </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
        <%= form.label :body %>
        <%= form.rich_text_area :body, class: 'form-control', rows: 12 %>
      </div>
    </div>
  </div>
  
  <hr>

  <div class="col-md-12">

  <h2>Technologies Used</h2>
    <div>
      <%= form.fields_for :technologies do |technology_form| %>
        <%= render partial: 'technology_fields', :locals => { :form => technology_form }  %>
      <% end %>
    </div>
    <div>
      <%= link_to_add_nested(form, :technologies, '#Add-Technology', partial: 'technology_fields') %>
    </div>

    <div class="form-group">
      <%= form.submit "Save Portfolio Item", class: 'btn btn-primary btn-block'%>
    </div>
    <% end %>
  </div>

app/views/portfolios/_portfolio_item.html.erb
<div data-id="<%= portfolio_item.id %>"  class="card portfolio-card col-md-4">
  <p class="card-text">
    <span>
      <%= link_to (image_tag (portfolio_item.main_image_url(:thumb).to_s), width: '100%'), portfolio_show_path(portfolio_item) %>
    </span>
      <%= portfolio_item.subtitle %>
  </p>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields" id=Add-Technology>
  <%= form.label :name %>
  <%= form.text_field :name, class: 'form-control' %>
  <%= link_to_remove_nested(form, link_text: 'Remove Item') %>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit the Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
      <%= source_helper("alert alert-warning") %>
    <div class="row sortable" data-controller="draggable" data-draggable-resource-value="portfolio_item" data-drag-url-value="" data-draggable-attribute-value="position" data-draggable-target="list">
      <%= render partial: 'portfolio_item', collection: @portfolio_items.order(position: :asc) %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Create a new Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag @portfolio_item.main_image_url.to_s, width: '100%' %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>
      <hr>
      <em><%= @portfolio_item.subtitle %></em>
      <p><%= @portfolio_item.body %></p>
      <hr>
      <h3>Technologies Used:</h3>
      <% @portfolio_item.technologies.each do |t| %>
      <p><%= t.name %></p>
      <% end %>
      <% if authorized_to %>
        <nav class="breadcrumb blogcrumb">
          <%= link_to fa_icon('pencil-square-o'), edit_portfolio_path(@portfolio_item) %>
          <%= link_to fa_icon('trash'), @portfolio_item, data: { turbo_method: :delete,
                        turbo_confirm: 'Are you sure?' } %>
        </nav>
      <% end %>
    </div>
  </div>
</div>