config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]


  resources :blogs do
    resources :comments, module: :blogs, only: %i[index create]
  end

  devise_scope :user do
    get "users", to: "devise/sessions#new"
  end

  devise_for :users, path: '',
                path_names: {
                sign_in: 'login',
                sign_out: 'logout',
                sign_up: 'register'
                            }

  resources :portfolios, except: [:show]

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-dark bg-dark">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">
    <%= link_to "Stuart Wilson", root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse nav-masthead" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li'%>
        <%= login_helper 'nav-link' %>
      </ul>
    </div>
  </div>
</nav>


<%#

 <div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Stuart Wilson</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
<%#      <%= login_helper 'nav-link' %>
<%#    </nav>
  </div>
</div>
<%
=end%>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
    
  <p>
    <%= link_to "Back to Blogs", blogs_path %> | 
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">A blog built with Bootstrap and Actiontext in Rails.</p>
    <span>
      <%= link_to 'Create', new_blog_path, class: 'btn btn-outline-primary' if authorized_to %>
    </span>
    <span>
      <%= link_to 'Topics', topics_path, class: 'btn btn-outline-primary' %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">
    <%= link_to "Stuart Wilson", root_path, class: 'navbar-brand'%>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li'%>
        <%= login_helper 'nav-link' %>
      </ul>
    </div>
  </div>
</nav>





<%#

 <div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%#= login_helper 'nav-link' %>
 <%#>   </nav>
  </div>
</div> 
<%
=end
%>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>A blog about technology, life, and whatever I am feeling opinionated about that day. It certainly won't <em>all </em> be great content... but, what do you expect for free?</p>
  </div>

    <%= source_helper("alert alert-info blog-sidebar-source") %>

  <% if @side_bar_topics %>
    <div class="sidebar-module">
      <h4>Topics</h4>
      <% @side_bar_topics.each do |topic| %>
        <p><%= link_to topic.title, topic_path(topic) %></p>
      <% end %>
    </div>
  <% end %>

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/DebakeDSP94"><%= fa_icon "github" %></a></li>
      <li><a href="https://www.linkedin.com/in/stuart-wilson-72b61a10/"><%= fa_icon "linkedin" %></a></li>
      <li><a href="https://twitter.com/StuartW64954805"><%= fa_icon "twitter" %></a></li>
      <li><a href="https://www.facebook.com/stuart.wilson.16568"><%= fa_icon "facebook" %></a></li>
      <li><a href="https://www.instagram.com/slw2014/"><%= fa_icon "instagram" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_flash.html.erb
<div class="">
  <div data-controller="alert" class="card bread <%= flash_class(level) %>">
    <div class="card-body">
      <p class="content">
        <%= content %>
      </p>
    </div>
    <div class="button-container">
      <button data-action="alert#close" class="btn close-flash <%= flash_class(level) %>">
        <%= inline_svg_tag 'close.svg', class: 'svgbtn', style: 'color: white' %>
      </button>
    </div>
  </div>
</div>

app/views/shared/_flash_container.html.erb
  <div id="flash-container">
    <% flash.each do |key, value| %>
      <%= render "shared/flash", level: key, content: value %>
    <% end %>
  </div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted portfolio-footer mastfoot">
  <div class="container">
    <p class="float-right">
      <%= link_to "View all portfolio items", portfolios_path %> | 
      <a href="#">Back to top</a> | 
      <%= link_to "Create New Item", new_portfolio_path if authorized_to %>
    </p>
    
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">This page contains examples of projects I have completed.  You can click on any of them to get a more detailed view, along with a description and a list of technologies used.  In many cases there is also a link to the github repo and a live version of the project.</p>
    <p>
      <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary'%>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">This page contains examples of projects I have completed.  You can click on any of them to get a more detailed view, along with a description and a list of technologies used.  In many cases there is also a link to the github repo and a live version of the project.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
            <%= nav_helper 'text-white', 'li' %>

            <li><%= login_helper 'text-white' %></li>

        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <%= link_to "Stuart Wilson", root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>